export const ActionTypes = {
  FETCH_USER: "FETCH_USER",
  ERRORS: "ERRORS",
  // For Login/Logout
  AUTH: "AUTH",
  AUTHRESPONSE: "AUTHRESPONSE",

  ADDUSER: "ADDUSER",
  SINGLEUSER: "SINGLEUSER",
  UPDATESINGLEUSER: "UPDATESINGLEUSER",
  DELETEUSER: "DELETEUSER",
  USERSTATUSRES: "USERSTATUSRES",
  USER_HIRING: "USER_HIRING",

  ALL_COUNTRIES: "ALL_COUNTRIES",
  FETCH_TRADIE: "FETCH_TRADIE",
  ADD_TRADIE: "ADD_TRADIE",
  TRADIE_APPROVAL: "TRADIE_APPROVAL",
  EDIT_TRADIE: "EDIT_TRADIE",
  JOBS_BY_TRADIE: "JOBS_BY_TRADIE",
  TRADIE_SUBSCRIPTION: "TRADIE_SUBSCRIPTION",
  TRADIE_LOADER: "TRADIE_LOADER",

  ALL_JOBS: "ALL_JOBS",
  SINGLE_JOBS: "SINGLE_JOBS",
  //  // For Change job status and delete
  JOBS_STATUS: "JOBS_STATUS",
  // Category Types
  CAT_LIST: "CAT_LIST",
  CAT_ADD: "CAT_ADD",
  SINGLE_CAT: "SINGLE_CAT",
  EDIT_CAT: "EDIT_CAT",
  STATUS_CAT: "STATUS_CAT",
  CAT_DEL: "CAT_DEL",
  CAT_JOB: "CAT_JOB",
  CAT_TRADIE: "CAT_TRADIE",
  // For Dashboard
  DASHBOARD: "DASHBOARD",
  GRAPH_DASHBOARD: "GRAPH_DASHBOARD",

  FAQ: "FAQ",
  FAQ_SINGLE: "FAQ_SINGLE",
  FAQ_ADD: "FAQ_ADD",
  FAQ_EDIT: "FAQ_EDIT",
  FAQ_DELETE: "FAQ_DELETE",
  FAQ_CAT: "FAQ_CAT",

  BLOG: "BLOG",
  SINGLE_BLOG: "SINGLE_BLOG",
  BLOG_ADD: "BLOG_ADD",
  BLOG_EDIT: "BLOG_EDIT",
  BLOG_DEL: "BLOG_DEL",
  NEWSLETTER: "NEWSLETTER",
  NEWSLETTER_DEL: "NEWSLETTER_DEL",

  TRADIE_TV: "TRADIE_TV",
  SINGLE_TRADIE_TV: "SINGLE_TRADIE_TV",
  ADD_TRADIE_TV: "ADD_TRADIE_TV",
  EDIT_TRADIE_TV: "EDIT_TRADIE_TV",
  DELETE_TRADIE_TV: "DELETE_TRADIE_TV",
  TRADIE_TV_CATEGORY: "TRADIE_TV_CATEGORY",
  //
  CONTACT_US: "CONTACT_US",
  CONTACT_US_DEL: "CONTACT_US_DEL",
  CONTACT_US_STATUS: "CONTACT_US_STATUS",

  RATING: "RATING",
  RATING_DELETE: "RATING_DELETE",

  TNC_LIST: "TNC_LIST",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  ABOUT_US: "ABOUT_US",
  ABOUT_US_UPDATE: "ABOUT_US_UPDATE",
  LEADS: "LEADS",
  BANNER: "BANNER",
  SINGLE_BANNER: "SINGLE_BANNER",
  UPDATE_BANNER: "UPDATE_BANNER",

  LOADER: "LOADER",
  SUBS_LOADER: "SUBS_LOADER",

  SUPPORT_LIST: "SUPPORT_LIST",
  SUBSCRIPTION_LIST: "SUBSCRIPTION_LIST",
  TOTAL_PAYMENT: "TOTAL_PAYMENT",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
};
