import { combineReducers } from "redux";
import {
  userReducer,
  authReducer,
  addUserReducer,
  editUserReducer,
  deleteUserReducer,
  userHiringsReducer,
  TradieReducer,
  editTradieReducer,
  countriesReducer,
  allJobsReducer,
  singleJobsReducer,
  jobStatusReducer,
  categoryReducer,
  dashboardReducer,
  faqReducer,
  blogReducer,
  newsletterReducer,
  tradieTvReducer,
  contactusReducer,
  ratingReducer,
  tncReducer,
  policyReducer,
  aboutUsReducer,
  leadReducer,
  bannerReducer,
  settingsReducer,
  supportReducer,
  loaderReducer,
  subscriptionReducer,
} from "./allReducer";

const reducers = combineReducers({
  user: userReducer,
  error: userReducer,
  auth: authReducer,
  response: authReducer,
  addUsers: addUserReducer,
  singleUser: editUserReducer,
  updateUserRes: editUserReducer,
  deleteUserRes: deleteUserReducer,
  userHiring: userHiringsReducer,
  userStatus: deleteUserReducer,
  allCountries: countriesReducer,
  tradieList: TradieReducer,
  approvalTradieRes: TradieReducer,
  addTradieRes: TradieReducer,
  jobsByTradieList: TradieReducer,
  editTradieRes: editTradieReducer,
  allJobs: allJobsReducer,
  singleJobs: singleJobsReducer,
  // For Change job status and delete
  job_status: jobStatusReducer,
  categoriesList: categoryReducer,
  SingleCat: categoryReducer,
  categoriesAdd: categoryReducer,
  serviceStatusRes: categoryReducer,
  categorieseDel: categoryReducer,
  jobsByService: categoryReducer,
  tradiesByService: categoryReducer,
  dashboardData: dashboardReducer,
  dashboardGraphData: dashboardReducer,
  faqData: faqReducer,
  faqS: faqReducer,
  faqRes: faqReducer,
  faqDelRes: faqReducer,
  faqCat: faqReducer,
  blogList: blogReducer,
  singleBlogD: blogReducer,
  blogAddRes: blogReducer,
  blogDelRes: blogReducer,
  newsletter: newsletterReducer,
  newsletterRes: newsletterReducer,
  TradieTvData: tradieTvReducer,
  TradieTvSin: tradieTvReducer,
  TradieTvRes: tradieTvReducer,
  TradieTvDelRes: tradieTvReducer,
  TradieTvCat: tradieTvReducer,
  //ContactUs
  contactUsList: contactusReducer,
  contactUsDel: contactusReducer,
  contactUsSts: contactusReducer,

  Support_List: supportReducer,
  Subscription_List: subscriptionReducer,
  // rating
  ratingList: ratingReducer,
  ratingDelRes: ratingReducer,

  loading: loaderReducer,
  TNCListD: tncReducer,
  PolicyList: policyReducer,
  aboutusList: aboutUsReducer,
  aboutusRes: aboutUsReducer,
  leadData: leadReducer,
  bannerData: bannerReducer,
  singleBanner: bannerReducer,
  updateBannerRes: bannerReducer,
  passwordChange: settingsReducer,
});

export default reducers;
